config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  resources :home
  resources :groups

end

app/models/group.rb
class Group < ActiveRecord::Base

	has_and_belongs_to_many :groups

	def email_info(emails)
		
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_and_belongs_to_many :groups

   validates :name, :presence => true, length: { maximum: 20 }
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

	#permit parameters for sign up
	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmartion) }
	end

	def after_sign_in_path_for(resource_or_scope)
    home_index_path
	end

	def after_sign_out_path_for(resource_or_scope)
	  new_user_session_path
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	def new
		@group = Group.new
	end

	def create
		@emails = params[:email].split(",").map(&:strip)
		@group = Group.new(group_params)
  end



	def group_params
		params.require(:group).permit(:name)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

	# render bootstrap class according to flash type
  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-danger"
      when :alert
        "alert-warning"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/groups/new.js.erb
$('#myModal').html("<%= j render '/groups/shared/create_group' %>");
$('#myModal').modal('show');

app/views/groups/shared/_create_group.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @group, :remote => true do |f| %>
      <div class="modal-header">
        <button aria-hidden="true" class="close" data-dismiss="modal" type="button">&times;</button>
        <h4 class="modal-title">Create Group</h4>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <label for="name">Group Name</label>
          <%= f.text_field :name, :class =>"form-control", :placeholder => "Group Name" %>
        </div>
        <div class="form-group">
          <label for="emails">Enter emails to send invitations for joining the group</label>
          <%= text_area_tag :emails,nil ,:class =>"form-control", :placeholder => "enter emails separated by comma" %>
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
        <%= f.submit "Create", :class => "btn btn-default " %>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.haml
= link_to 'Create Group', '#', :class => 'btn btn-primary btn-lg'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render '/layouts/shared/header' %>
	<div class=<%= "center-align" unless flash.blank? %>>
    <%= render partial: "/layouts/shared/flash_messages", flash: flash %>
  </div>
	<%= yield %>
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	</div>
</body>
</html>

app/views/layouts/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
<% end %>

app/views/layouts/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    	<ul class="nav navbar-nav navbar-left">
    	<li><%= link_to "Welcome #{current_user.name} !", '#' if user_signed_in? %></li>
    	</ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        	<li><%= link_to "Create Group",  new_group_path, :class => 'static-popup-link ', :remote => true %></li>
				  <li><%= link_to "Change Password",  edit_user_password_path %></li>
				  <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
				
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Settings <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Edit password', edit_user_password_path %></li>
            </ul>
          </li>

        <% else %>
					<li><%= link_to "Login", new_user_session_path unless user_signed_in? %></li>
					<li><%= link_to "Sign Up",new_user_registration_path %></li>
				<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>